import type { Metadata } from "next";
import nextFontLocal from "next/font/local";
import "./globals.css";

const fontSans = nextFontLocal({
  src: [
    {
      path: "../../public/fonts/Bevellier-Thin.otf",
      weight: "100",
      style: "normal",
    },
    {
      path: "../../public/fonts/Bevellier-Extralight.otf",
      weight: "200",
      style: "normal",
    },
    {
      path: "../../public/fonts/Bevellier-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/fonts/Bevellier-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/Bevellier-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/Bevellier-Semibold.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/fonts/Bevellier-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/Bevellier-Black.otf",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontSans.variable} antialiased`}>{children}</body>
    </html>
  );
}
