export const products = [
  {
    id: "1",
    name: "Nike Air Max 90 SE",
    description: "The Air Max 90 stays true to its running roots with the iconic Waffle sole. Plus, stitched overlays and textured accents create the '90s look you love. Complete with romantic hues, its visible Air cushioning adds comfort to your journey.",
    category: "Women's Shoes",
    styleNumber: "HM9451-600",
    price: 140.00,
    gender: "women",
    sizes: ["5.0", "5.5", "6.0", "6.5", "7.0", "7.5", "8.0", "8.5"],
    colors: [
      { name: "Red", hex: "#FF0000" },
      { name: "White", hex: "#FFFFFF" },
    ],
    images: ["/shoes/shoe-1.jpg"],
  },
  {
    id: "2",
    name: "Nike Air Force 1 '07",
    description: "The radiance lives on in the Nike Air Force 1 '07, the basketball original that puts a fresh spin on what you know best: durably stitched overlays, clean finishes and the perfect amount of flash to make you shine.",
    category: "Men's Shoes",
    styleNumber: "CW2288-111",
    price: 110.00,
    gender: "men",
    sizes: ["8.0", "8.5", "9.0", "9.5", "10.0", "10.5", "11.0", "11.5"],
    colors: [
      { name: "White", hex: "#FFFFFF" },
      { name: "Black", hex: "#000000" },
    ],
    images: ["/shoes/shoe-2.webp"],
  },
  {
    id: "3",
    name: "Nike Dunk Low",
    description: "Created for the hardwood but taken to the streets, the '80s b-ball icon returns with perfectly sheened overlays and original team colors. With its classic hoops design, the Nike Dunk Low channels '80s vintage back onto the streets while its padded, low-cut collar lets you take your game anywhere—in comfort.",
    category: "kid's Shoes",
    styleNumber: "DD1391-100",
    price: 100.00,
    gender: "kids",
    sizes: ["1.0", "1.5", "2.0", "2.5", "3.0", "3.5"],
    colors: [
      { name: "White", hex: "#FFFFFF" },
      { name: "Red", hex: "#FF0000" },
    ],
    images: ["/shoes/shoe-3.webp"],
  },
  {
    id: "4",
    name: "Nike Air Max 270",
    description: "Nike's first lifestyle Air Max brings you style, comfort and big attitude in the Nike Air Max 270. The design draws inspiration from Air Max icons, showcasing Nike's greatest innovation with its large window and fresh array of colors.",
    category: "Unisex Shoes",
    styleNumber: "AH6789-100",
    price: 130.00,
    gender: "unisex",
    sizes: ["5.0", "5.5", "6.0", "6.5", "7.0", "7.5", "8.0", "8.5", "9.0", "9.5", "10.0"],
    colors: [
      { name: "White", hex: "#FFFFFF" },
      { name: "Black", hex: "#000000" },
    ],
    images: ["/shoes/shoe-4.webp"],
  },
  {
    id: "5",
    name: "Nike Blazer Mid '77 Vintage",
    description: "In the '70s, Nike was the new shoe on the block. So new in fact, we were still making them in a small workshop in Beaverton. Fast forward a few decades and the Nike Blazer Mid '77 Vintage returns with classic details and throwback hoops flair.",
    category: "Unisex Shoes",
    styleNumber: "BQ6806-100",
    price: 90.00,
    gender: "unisex",
    sizes: ["5.0", "5.5", "6.0", "6.5", "7.0", "7.5", "8.0", "8.5"],
    colors: [
      { name: "White", hex: "#FFFFFF" },
      { name: "Black", hex: "#000000" },
    ],
    images: ["/shoes/shoe-5.avif"],
  },
  {
    id: "6",
    name: "Nike Air Max 1",
    description: "Meet the leader of the pack. Walking on air since 1987, the Air Max 1 won't be going anywhere soon. The timeless silhouette feels as good as it looks, with the perfect amount of flash to make you shine.",
    category: "kid's Shoes",
    styleNumber: "DH4059-101",
    price: 120.00,
    gender: "kids",
    sizes: ["1.0", "1.5", "2.0", "2.5", "3.0"],
    colors: [
      { name: "White", hex: "#FFFFFF" },
      { name: "Red", hex: "#FF0000" },
    ],
    images: ["/shoes/shoe-6.avif"],
  },
  {
    id: "7",
    name: "Nike Air Jordan 1 Low",
    description: "Inspired by the original that debuted in 1985, the Air Jordan 1 Low offers a clean, classic look that's familiar yet always fresh. With an iconic design that pairs perfectly with any fit, these kicks ensure you'll always be on point.",
    category: "Men's Shoes",
    styleNumber: "553558-161",
    price: 90.00,
    gender: "men",
    sizes: ["8.0", "8.5", "9.0", "9.5", "10.0", "10.5", "11.0"],
    colors: [
      { name: "White", hex: "#FFFFFF" },
      { name: "Black", hex: "#000000" },
    ],
    images: ["/shoes/shoe-7.avif"],
  },
  {
    id: "8",
    name: "Nike React Infinity Run Flyknit 3",
    description: "A shoe designed to help you run more. The Nike React Infinity Run Flyknit 3 continues to help reduce injury and keep you on the run. More foam and improved upper details provide a secure and cushioned feel.",
    category: "Women's Shoes",
    styleNumber: "CT2357-002",
    price: 160.00,
    gender: "women",
    sizes: ["5.0", "5.5", "6.0", "6.5", "7.0", "7.5", "8.0"],
    colors: [
      { name: "Black", hex: "#000000" },
      { name: "White", hex: "#FFFFFF" },
    ],
    images: ["/shoes/shoe-8.avif"],
  },
  {
    id: "9",
    name: "Nike Cortez",
    description: "The Nike Cortez continues to deliver the comfort and simple style that made it an instant hit back in 1972. A cult classic with a track legacy, it pairs a nylon upper with suede accents and the signature waffle-pattern outsole.",
    category: "Men's Shoes",
    styleNumber: "807471-101",
    price: 80.00,
    gender: "men",
    sizes: ["8.0", "8.5", "9.0", "9.5", "10.0", "10.5", "11.0", "11.5", "12.0"],
    colors: [
      { name: "White", hex: "#FFFFFF" },
      { name: "Red", hex: "#FF0000" },
    ],
    images: ["/shoes/shoe-9.avif"],
  },
  {
    id: "10",
    name: "Nike Air Max 97",
    description: "Featuring the original ripple design inspired by Japanese bullet trains, the Nike Air Max 97 lets you push your style full-speed ahead. Taking the revolutionary full-length Nike Air unit that shook up the running world and adding fresh colors and crisp details, it lets you ride in first-class comfort.",
    category: "Unisex Shoes",
    styleNumber: "DH4069-101",
    price: 170.00,
    gender: "unisex",
    sizes: ["5.0", "5.5", "6.0", "6.5", "7.0", "7.5", "8.0", "8.5", "9.0"],
    colors: [
      { name: "White", hex: "#FFFFFF" },
      { name: "Gray", hex: "#808080" },
    ],
    images: ["/shoes/shoe-10.avif"],
  },
  {
    id: "11",
    name: "Nike Pegasus 40",
    description: "A springy ride for every run, the Peg's familiar, just-for-you feel returns to help you accomplish your goals. This version has the same responsiveness and neutral support you love but with improved comfort in those sensitive areas of your foot, like the arch and toes.",
    category: "kid's Shoes",
    styleNumber: "DV3853-101",
    price: 130.00,
    gender: "kids",
    sizes: ["1.0", "1.5", "2.0", "2.5", "3.0", "3.5", "4.0"],
    colors: [
      { name: "White", hex: "#FFFFFF" },
      { name: "Silver", hex: "#C0C0C0" },
    ],
    images: ["/shoes/shoe-11.avif"],
  },
  {
    id: "12",
    name: "Nike SB Dunk Low Pro",
    description: "Created for the hardwood but taken to the streets, the basketball icon returns with classic details and throwback hoops flair. Its vintage outsole is combined with a soft sockliner and Nike Zoom Air unit for a comfortable ride that can take on any street session.",
    category: "Women's Shoes",
    styleNumber: "BQ6817-005",
    price: 90.00,
    gender: "women",
    sizes: ["5.0", "5.5", "6.0", "6.5", "7.0", "7.5"],
    colors: [
      { name: "Black", hex: "#000000" },
      { name: "White", hex: "#FFFFFF" },
    ],
    images: ["/shoes/shoe-12.avif"],
  },
];
